- hosts: localhost
  connection: local
  become: true

  tasks:
  - debug:
  var: ansible_facts

  - name: Create system facts file
    ansible.builtin.copy:
      src: "{{ ansible_facts }}"
      dest: ~/ansible_system_facts.txt




