- hosts: localhost
  connection: local
  become: true

  tasks:
    
  - setup: 
    register: setupvar


  - name: Create system facts file
    ansible.builtin.copy:
      src: "{{ setupvar.ansible_facts }}"
      dest: ~/ansible_system_facts.txt




