- hosts: localhost
  connection: local
  become: true

  tasks:
  - debug:
  var: ansible_facts

  - local_action:
        module: copy
        content: "{{ ansible_facts }}"
        dest: ~/ansible_system_facts




